
    create table Categoria (
        id bigint generated by default as identity (start with 1),
        nombre varchar(255),
        primary key (id)
    )

    create table Empresa (
        clasificacion integer,
        id bigint not null,
        primary key (id)
    )

    create table Entidad (
        id bigint generated by default as identity (start with 1),
        nombreFicticio varchar(255),
        primary key (id)
    )

    create table EntidadBase (
        descripcion varchar(255),
        id bigint not null,
        primary key (id)
    )

    create table EntidadJuridica (
        codigoIGJ integer not null,
        cuit varchar(255),
        altura integer not null,
        calle varchar(255),
        ciudad varchar(255),
        codigoPostal varchar(255),
        pais varchar(255),
        piso integer not null,
        provincia varchar(255),
        razonSocial varchar(255),
        id bigint not null,
        primary key (id)
    )

    create table Entidad_Categoria (
        Entidad_id bigint not null,
        categorias_id bigint not null
    )

    create table Item (
        id bigint generated by default as identity (start with 1),
        cantidad integer not null,
        descripcion varchar(255),
        valorUnitario numeric,
        primary key (id)
    )

    create table OrganizacionSectorSocial (
        id bigint not null,
        primary key (id)
    )

    create table Presupuesto (
        id bigint generated by default as identity (start with 1),
        elegido boolean not null,
        id_compra bigint,
        primary key (id)
    )

    create table Proveedor (
        id bigint generated by default as identity (start with 1),
        apellido varchar(255),
        cuil integer not null,
        altura integer not null,
        calle varchar(255),
        ciudad varchar(255),
        codigoPostal varchar(255),
        pais varchar(255),
        piso integer not null,
        provincia varchar(255),
        dni integer not null,
        nombre varchar(255),
        razonSocial varchar(255),
        primary key (id)
    )

    create table Usuario (
        id bigint generated by default as identity (start with 1),
        contrasenia varchar(255),
        username varchar(255),
        primary key (id)
    )

    create table compras (
        id bigint generated by default as identity (start with 1),
        cantidadMinimaDePresupuestos integer not null,
        fechaOperacion varbinary(255),
        indicadorDeAprobacion integer,
        codigo varchar(255),
        descripcion varchar(255),
        entidadRelacionada_id bigint,
        primary key (id)
    )

    create table entidades_por_entidad_juridica (
        EntidadJuridica_id bigint not null,
        entidadesBase_id bigint not null
    )

    create table etiquetas (
        Compra_id bigint not null,
        etiqueta varchar(255)
    )

    create table items_por_compra (
        compras_id bigint not null,
        items_id bigint not null
    )

    create table items_por_presupuesto (
        Presupuesto_id bigint not null,
        items_id bigint not null
    )

    create table validadores_por_compra (
        compras_id bigint not null,
        usuariosValidadores_id bigint not null
    )

    alter table entidades_por_entidad_juridica 
        add constraint UK_pwukomg1tyi1r7duq97aoh0qu  unique (entidadesBase_id)

    alter table Empresa 
        add constraint FK_eg477mv2yqmlrfnj2svapcprm 
        foreign key (id) 
        references EntidadJuridica

    alter table EntidadBase 
        add constraint FK_8r7yhl4vpqnlkm6ddaa4rpd6c 
        foreign key (id) 
        references Entidad

    alter table EntidadJuridica 
        add constraint FK_pcrp9vdj0cllsldpnw126n1be 
        foreign key (id) 
        references Entidad

    alter table Entidad_Categoria 
        add constraint FK_s6lx3rwe4oqx3slcepdijark 
        foreign key (categorias_id) 
        references Categoria

    alter table Entidad_Categoria 
        add constraint FK_8tllpn7vnk9cdwiflecywem0p 
        foreign key (Entidad_id) 
        references Entidad

    alter table OrganizacionSectorSocial 
        add constraint FK_7h2ed9l50goamxupg47gkg9rq 
        foreign key (id) 
        references EntidadJuridica

    alter table Presupuesto 
        add constraint FK_p6d07h6ydu4cl7ggsun0xm0nd 
        foreign key (id_compra) 
        references compras

    alter table compras 
        add constraint FK_d4fvwrtyoxa84mcbp0boi72yc 
        foreign key (entidadRelacionada_id) 
        references Entidad

    alter table entidades_por_entidad_juridica 
        add constraint FK_pwukomg1tyi1r7duq97aoh0qu 
        foreign key (entidadesBase_id) 
        references EntidadBase

    alter table entidades_por_entidad_juridica 
        add constraint FK_acs2jbx507plggq7gj1wvba2d 
        foreign key (EntidadJuridica_id) 
        references EntidadJuridica

    alter table etiquetas 
        add constraint FK_kgnt82id6hv86a41vwpolordy 
        foreign key (Compra_id) 
        references compras

    alter table items_por_compra 
        add constraint FK_3gm872uq85loo58rom6l3kc9b 
        foreign key (items_id) 
        references Item

    alter table items_por_compra 
        add constraint FK_ce444s522y9mge2weig04i31o 
        foreign key (compras_id) 
        references compras

    alter table items_por_presupuesto 
        add constraint FK_qafhck1g6vh5tg43in457pfxc 
        foreign key (items_id) 
        references Item

    alter table items_por_presupuesto 
        add constraint FK_ouibfogomesm9l0oukuivb5d3 
        foreign key (Presupuesto_id) 
        references Presupuesto

    alter table validadores_por_compra 
        add constraint FK_dja349lyqivfwr7hxand1eo96 
        foreign key (usuariosValidadores_id) 
        references Usuario

    alter table validadores_por_compra 
        add constraint FK_6cg806y2itg3h1avpddg9octg 
        foreign key (compras_id) 
        references compras
